FROM ruby:2.6.3-slim-buster

RUN apt-get update -qq \
  && apt-get install -y \
    build-essential \
    cmake \
    curl \
    wget \
    software-properties-common \
    pkg-config \
    libsasl2-dev \
    percona-toolkit \
    wait-for-it \
    socat \
    git \
  # --- mysql
  && echo "mysql-apt-config mysql-apt-config/select-server select mysql-5.7" | /usr/bin/debconf-set-selections \
  && curl -L -o /tmp/mysql-apt-config_0.8.13-1_all.deb https://dev.mysql.com/get/mysql-apt-config_0.8.13-1_all.deb \
  && DEBIAN_FRONTEND=noninteractive dpkg -i /tmp/mysql-apt-config_0.8.13-1_all.deb \
  && apt-get update -qq \
  && apt-get install -y mysql-community-client libmysqlclient-dev \
  # --- cleanup
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/*

WORKDIR /opt/app
